import os

import pytest
from cryptography.fernet import Fernet, InvalidToken

import services.crypto as crypto


@pytest.fixture(autouse=True)
def _reset_fernet_singleton():
    """每个测试后重置懒加载单例，避免跨测试污染 key 解析结果。"""
    crypto._fernet.cache_clear()
    yield
    crypto._fernet.cache_clear()


def test_encrypt_decrypt_roundtrip():
    enc = crypto.encrypt_secret("sk-super-secret")
    assert enc.startswith("enc:")
    assert enc != "sk-super-secret"
    assert crypto.decrypt_secret(enc) == "sk-super-secret"


def test_empty_string_passes_through_unchanged():
    assert crypto.encrypt_secret("") == ""
    assert crypto.decrypt_secret("") == ""


def test_legacy_plaintext_passthrough_in_decrypt():
    assert crypto.decrypt_secret("sk-plain-legacy-key") == "sk-plain-legacy-key"


def test_is_encrypted():
    enc = crypto.encrypt_secret("sk-x")
    assert crypto.is_encrypted(enc) is True
    assert crypto.is_encrypted("sk-plain") is False
    assert crypto.is_encrypted("") is False


def test_decrypt_wrong_key_raises_clear_runtime_error(monkeypatch):
    enc = crypto.encrypt_secret("sk-x")
    crypto._fernet.cache_clear()
    monkeypatch.setenv("PROMPTSCOPE_ENCRYPTION_KEY", Fernet.generate_key().decode())
    with pytest.raises(RuntimeError, match="PROMPTSCOPE_ENCRYPTION_KEY"):
        crypto.decrypt_secret(enc)


def test_key_file_autogenerated_when_env_unset(tmp_path, monkeypatch):
    monkeypatch.delenv("PROMPTSCOPE_ENCRYPTION_KEY", raising=False)
    key_path = tmp_path / ".encryption_key"
    monkeypatch.setattr(crypto, "_KEY_FILE_PATH", str(key_path))

    assert not key_path.exists()
    enc = crypto.encrypt_secret("sk-x")
    assert key_path.exists()
    # 0o600 权限
    assert (key_path.stat().st_mode & 0o777) == 0o600
    assert crypto.decrypt_secret(enc) == "sk-x"


def test_key_file_reused_on_second_call(tmp_path, monkeypatch):
    monkeypatch.delenv("PROMPTSCOPE_ENCRYPTION_KEY", raising=False)
    key_path = tmp_path / ".encryption_key"
    monkeypatch.setattr(crypto, "_KEY_FILE_PATH", str(key_path))

    crypto.encrypt_secret("sk-a")  # 生成 key 文件
    first_key = key_path.read_bytes()
    crypto._fernet.cache_clear()
    enc = crypto.encrypt_secret("sk-b")
    assert key_path.read_bytes() == first_key
    assert crypto.decrypt_secret(enc) == "sk-b"


def test_migrate_plaintext_provider_keys(db_session):
    from models.entities import ModelProvider

    plain = ModelProvider(name="legacy", base_url="https://api.test.com",
                          api_key="sk-legacy-plaintext", provider_type="openai")
    already_enc = ModelProvider(name="already-enc", base_url="https://api.test.com",
                                api_key=crypto.encrypt_secret("sk-already"),
                                provider_type="openai")
    empty = ModelProvider(name="empty", base_url="https://api.test.com",
                          api_key="", provider_type="openai")
    db_session.add_all([plain, already_enc, empty])
    db_session.commit()

    count = crypto.migrate_plaintext_provider_keys(db_session)
    assert count == 1

    db_session.refresh(plain)
    db_session.refresh(already_enc)
    db_session.refresh(empty)
    assert crypto.is_encrypted(plain.api_key)
    assert crypto.decrypt_secret(plain.api_key) == "sk-legacy-plaintext"
    assert crypto.decrypt_secret(already_enc.api_key) == "sk-already"
    assert empty.api_key == ""

    # 幂等：第二次运行不再重复加密任何行
    second_count = crypto.migrate_plaintext_provider_keys(db_session)
    assert second_count == 0
    db_session.refresh(plain)
    assert crypto.decrypt_secret(plain.api_key) == "sk-legacy-plaintext"
